version: "2.2"
services:
  app:
    build: ./.docker/node/build
    user: node
    network_mode: host
    working_dir: /srv
    env_file:
      - ./.env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
    ports:
      - 3000
  firebase:
    build: ./.docker/node/build
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: node
    network_mode: host
    working_dir: /srv
    env_file:
      - ./.env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
    command: ["yarn", "firebase", "emulators:start"]
    ports:
      - 5001
      - 8080
      - 8081
  firebase-migrate:
    build: ./.docker/node/build
    user: node
    network_mode: host
    working_dir: /srv
    env_file:
      - ./.env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
    command: ["yarn", "firebase:seed"]
