version: "2.2"
services:
  node:
    build: ./.docker/node/build
    network_mode: host
    working_dir: /srv
    env_file:
      - ./.env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
  app:
    extends:
      service: node
    expose:
      - 3000
  firebase:
    build: ./.docker/node/build
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 60s
      retries: 5
    network_mode: host
    working_dir: /srv
    env_file:
      - ./.env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
    command: ["yarn", "firebase", "emulators:start"]
    expose:
      - 5001
      - 8080
      - 8081
  firebase-migrate:
    build: ./.docker/node/build
    network_mode: host
    working_dir: /srv
    env_file:
      - ./.env
    environment:
      PATH: /srv/node_modules/.bin:$PATH
    volumes:
      - ./:/srv
      - ./.docker/node/.cache:/home/node/.cache
      - ./.docker/node/.config:/home/node/.config
    command: ["yarn", "firebase:seed"]
