version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Configure
          command: |
            echo "GCLOUD_PROJECT=$GCLOUD_PROJECT" >> .env
            echo "FIRESTORE_EMULATOR_HOST=localhost:8080" >> .env
      - run:
          name: Build
          command: |
            docker-compose build
            sudo chown -R 1000:1000 ./
      - run:
          name: Install
          command: |
            ./bin/install
      - run:
          name: Test
          command: |
            ./bin/test
