version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build:
    executor:
      name: docker/docker
    environment:
      
    steps:
      - checkout
      - docker/install-docker-tools
      - run:
          name: Build services
          command: |
            docker-compose build
