name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
        run: |
          echo "GCLOUD_PROJECT=$GCLOUD_PROJECT" >> .env
          echo "FIRESTORE_EMULATOR_HOST=localhost:8080" >> .env
      - run: sudo ./bin/install
      - run: sudo ./bin/test
